//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GisDes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GisdesEntity : DbContext
    {
        public GisdesEntity()
            : base("name=GisdesEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<ActividadAsociadoGrupoInv> ActividadAsociadoGrupoInv { get; set; }
        public virtual DbSet<ActividadAsociadoSemilleroInv> ActividadAsociadoSemilleroInv { get; set; }
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<ArticuloAsociadoGrupoInv> ArticuloAsociadoGrupoInv { get; set; }
        public virtual DbSet<ArticuloAsociadoSemilleroInv> ArticuloAsociadoSemilleroInv { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Clasificacion> Clasificacion { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<EventoAsociadoGrupoInv> EventoAsociadoGrupoInv { get; set; }
        public virtual DbSet<EventoAsociadoSemilleroInv> EventoAsociadoSemilleroInv { get; set; }
        public virtual DbSet<GrupoInvestigacion> GrupoInvestigacion { get; set; }
        public virtual DbSet<Integrante> Integrante { get; set; }
        public virtual DbSet<IntegranteActividad> IntegranteActividad { get; set; }
        public virtual DbSet<IntegranteArticulo> IntegranteArticulo { get; set; }
        public virtual DbSet<IntegranteEvento> IntegranteEvento { get; set; }
        public virtual DbSet<IntegranteGrupoInvestigacion> IntegranteGrupoInvestigacion { get; set; }
        public virtual DbSet<IntegranteLibro> IntegranteLibro { get; set; }
        public virtual DbSet<IntegranteProyecto> IntegranteProyecto { get; set; }
        public virtual DbSet<IntegranteReconocimiento> IntegranteReconocimiento { get; set; }
        public virtual DbSet<IntegranteSemilleroInvestigacion> IntegranteSemilleroInvestigacion { get; set; }
        public virtual DbSet<Libro> Libro { get; set; }
        public virtual DbSet<LibroAsociadoGrupoInv> LibroAsociadoGrupoInv { get; set; }
        public virtual DbSet<LibroAsociadoSemilleroInv> LibroAsociadoSemilleroInv { get; set; }
        public virtual DbSet<LineaInvestigacion> LineaInvestigacion { get; set; }
        public virtual DbSet<NivelAcademico> NivelAcademico { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<ProyectoAsociadoGrupoInv> ProyectoAsociadoGrupoInv { get; set; }
        public virtual DbSet<ProyectoAsociadoSemilleroInv> ProyectoAsociadoSemilleroInv { get; set; }
        public virtual DbSet<ReconociemientoAsociadoGrupoInv> ReconociemientoAsociadoGrupoInv { get; set; }
        public virtual DbSet<ReconociemientoAsociadoSemilleroInv> ReconociemientoAsociadoSemilleroInv { get; set; }
        public virtual DbSet<Reconocimiento> Reconocimiento { get; set; }
        public virtual DbSet<SemilleroInvestigacion> SemilleroInvestigacion { get; set; }
        public virtual DbSet<TipoIntegrante> TipoIntegrante { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
