//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GisDes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estado()
        {
            this.Actividad = new HashSet<Actividad>();
            this.ActividadAsociadoGrupoInv = new HashSet<ActividadAsociadoGrupoInv>();
            this.ActividadAsociadoSemilleroInv = new HashSet<ActividadAsociadoSemilleroInv>();
            this.Articulo = new HashSet<Articulo>();
            this.ArticuloAsociadoGrupoInv = new HashSet<ArticuloAsociadoGrupoInv>();
            this.ArticuloAsociadoSemilleroInv = new HashSet<ArticuloAsociadoSemilleroInv>();
            this.Categoria = new HashSet<Categoria>();
            this.Clasificacion = new HashSet<Clasificacion>();
            this.EventoAsociadoGrupoInv = new HashSet<EventoAsociadoGrupoInv>();
            this.EventoAsociadoSemilleroInv = new HashSet<EventoAsociadoSemilleroInv>();
            this.Evento = new HashSet<Evento>();
            this.GrupoInvestigacion = new HashSet<GrupoInvestigacion>();
            this.Integrante = new HashSet<Integrante>();
            this.IntegranteGrupoInvestigacion = new HashSet<IntegranteGrupoInvestigacion>();
            this.IntegranteActividad = new HashSet<IntegranteActividad>();
            this.IntegranteArticulo = new HashSet<IntegranteArticulo>();
            this.IntegranteEvento = new HashSet<IntegranteEvento>();
            this.IntegranteLibro = new HashSet<IntegranteLibro>();
            this.IntegranteProyecto = new HashSet<IntegranteProyecto>();
            this.IntegranteReconocimiento = new HashSet<IntegranteReconocimiento>();
            this.IntegranteSemilleroInvestigacion = new HashSet<IntegranteSemilleroInvestigacion>();
            this.Libro = new HashSet<Libro>();
            this.LineaInvestigacion = new HashSet<LineaInvestigacion>();
            this.LibroAsociadoGrupoInv = new HashSet<LibroAsociadoGrupoInv>();
            this.LibroAsociadoSemilleroInv = new HashSet<LibroAsociadoSemilleroInv>();
            this.NivelAcademico = new HashSet<NivelAcademico>();
            this.Proyecto = new HashSet<Proyecto>();
            this.ProyectoAsociadoGrupoInv = new HashSet<ProyectoAsociadoGrupoInv>();
            this.ProyectoAsociadoSemilleroInv = new HashSet<ProyectoAsociadoSemilleroInv>();
            this.ReconociemientoAsociadoGrupoInv = new HashSet<ReconociemientoAsociadoGrupoInv>();
            this.ReconociemientoAsociadoSemilleroInv = new HashSet<ReconociemientoAsociadoSemilleroInv>();
            this.Reconocimiento = new HashSet<Reconocimiento>();
            this.SemilleroInvestigacion = new HashSet<SemilleroInvestigacion>();
            this.TipoIntegrante = new HashSet<TipoIntegrante>();
        }
    
        public decimal Id { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaUpdate { get; set; }
        public bool Estado1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividad> Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadAsociadoGrupoInv> ActividadAsociadoGrupoInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadAsociadoSemilleroInv> ActividadAsociadoSemilleroInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulo> Articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticuloAsociadoGrupoInv> ArticuloAsociadoGrupoInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticuloAsociadoSemilleroInv> ArticuloAsociadoSemilleroInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categoria> Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clasificacion> Clasificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoAsociadoGrupoInv> EventoAsociadoGrupoInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoAsociadoSemilleroInv> EventoAsociadoSemilleroInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evento> Evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoInvestigacion> GrupoInvestigacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Integrante> Integrante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteGrupoInvestigacion> IntegranteGrupoInvestigacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteActividad> IntegranteActividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteArticulo> IntegranteArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteEvento> IntegranteEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteLibro> IntegranteLibro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteProyecto> IntegranteProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteReconocimiento> IntegranteReconocimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteSemilleroInvestigacion> IntegranteSemilleroInvestigacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Libro> Libro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaInvestigacion> LineaInvestigacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibroAsociadoGrupoInv> LibroAsociadoGrupoInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibroAsociadoSemilleroInv> LibroAsociadoSemilleroInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NivelAcademico> NivelAcademico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyecto> Proyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoAsociadoGrupoInv> ProyectoAsociadoGrupoInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoAsociadoSemilleroInv> ProyectoAsociadoSemilleroInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReconociemientoAsociadoGrupoInv> ReconociemientoAsociadoGrupoInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReconociemientoAsociadoSemilleroInv> ReconociemientoAsociadoSemilleroInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reconocimiento> Reconocimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemilleroInvestigacion> SemilleroInvestigacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoIntegrante> TipoIntegrante { get; set; }
    }
}
