//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GisDes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoInvestigacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrupoInvestigacion()
        {
            this.ActividadAsociadoGrupoInv = new HashSet<ActividadAsociadoGrupoInv>();
            this.ArticuloAsociadoGrupoInv = new HashSet<ArticuloAsociadoGrupoInv>();
            this.EventoAsociadoGrupoInv = new HashSet<EventoAsociadoGrupoInv>();
            this.LineaInvestigacion = new HashSet<LineaInvestigacion>();
            this.IntegranteGrupoInvestigacion = new HashSet<IntegranteGrupoInvestigacion>();
            this.LibroAsociadoGrupoInv = new HashSet<LibroAsociadoGrupoInv>();
            this.ProyectoAsociadoGrupoInv = new HashSet<ProyectoAsociadoGrupoInv>();
            this.ReconociemientoAsociadoGrupoInv = new HashSet<ReconociemientoAsociadoGrupoInv>();
        }
    
        public decimal Id { get; set; }
        public string Nombre { get; set; }
        public decimal Coordinador { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public decimal Clasificacion { get; set; }
        public string AreaConocimiento { get; set; }
        public string GrupLac { get; set; }
        public System.DateTime FechaUpdate { get; set; }
        public Nullable<decimal> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadAsociadoGrupoInv> ActividadAsociadoGrupoInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticuloAsociadoGrupoInv> ArticuloAsociadoGrupoInv { get; set; }
        public virtual Clasificacion Clasificacion1 { get; set; }
        public virtual Estado Estado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoAsociadoGrupoInv> EventoAsociadoGrupoInv { get; set; }
        public virtual Integrante Integrante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaInvestigacion> LineaInvestigacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteGrupoInvestigacion> IntegranteGrupoInvestigacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibroAsociadoGrupoInv> LibroAsociadoGrupoInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoAsociadoGrupoInv> ProyectoAsociadoGrupoInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReconociemientoAsociadoGrupoInv> ReconociemientoAsociadoGrupoInv { get; set; }
    }
}
