//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GisDes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Integrante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Integrante()
        {
            this.GrupoInvestigacion = new HashSet<GrupoInvestigacion>();
            this.SemilleroInvestigacion = new HashSet<SemilleroInvestigacion>();
            this.IntegranteGrupoInvestigacion = new HashSet<IntegranteGrupoInvestigacion>();
            this.IntegranteActividad = new HashSet<IntegranteActividad>();
            this.IntegranteArticulo = new HashSet<IntegranteArticulo>();
            this.IntegranteEvento = new HashSet<IntegranteEvento>();
            this.IntegranteLibro = new HashSet<IntegranteLibro>();
            this.IntegranteProyecto = new HashSet<IntegranteProyecto>();
            this.IntegranteReconocimiento = new HashSet<IntegranteReconocimiento>();
            this.IntegranteSemilleroInvestigacion = new HashSet<IntegranteSemilleroInvestigacion>();
            this.Proyecto = new HashSet<Proyecto>();
        }
    
        public decimal Id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Documento { get; set; }
        public string Nacionalidad { get; set; }
        public string Sexo { get; set; }
        public string Cvlac { get; set; }
        public decimal NivelAcademico { get; set; }
        public string Correo { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public decimal TipoIntegrante { get; set; }
        public System.DateTime FechaUpdate { get; set; }
        public Nullable<decimal> Estado { get; set; }
    
        public virtual Estado Estado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoInvestigacion> GrupoInvestigacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemilleroInvestigacion> SemilleroInvestigacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteGrupoInvestigacion> IntegranteGrupoInvestigacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteActividad> IntegranteActividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteArticulo> IntegranteArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteEvento> IntegranteEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteLibro> IntegranteLibro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteProyecto> IntegranteProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteReconocimiento> IntegranteReconocimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteSemilleroInvestigacion> IntegranteSemilleroInvestigacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyecto> Proyecto { get; set; }
        public virtual NivelAcademico NivelAcademico1 { get; set; }
        public virtual TipoIntegrante TipoIntegrante1 { get; set; }
    }
}
