//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GisDes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaInvestigacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LineaInvestigacion()
        {
            this.SemilleroInvestigacion = new HashSet<SemilleroInvestigacion>();
        }
    
        public decimal Id { get; set; }
        public string Nombre { get; set; }
        public decimal GrupoInvestigacion { get; set; }
        public System.DateTime FechaUpdate { get; set; }
        public Nullable<decimal> Estado { get; set; }
    
        public virtual Estado Estado1 { get; set; }
        public virtual GrupoInvestigacion GrupoInvestigacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemilleroInvestigacion> SemilleroInvestigacion { get; set; }
    }
}
