//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GisDes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemilleroInvestigacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SemilleroInvestigacion()
        {
            this.ActividadAsociadoSemilleroInv = new HashSet<ActividadAsociadoSemilleroInv>();
            this.ArticuloAsociadoSemilleroInv = new HashSet<ArticuloAsociadoSemilleroInv>();
            this.EventoAsociadoSemilleroInv = new HashSet<EventoAsociadoSemilleroInv>();
            this.IntegranteSemilleroInvestigacion = new HashSet<IntegranteSemilleroInvestigacion>();
            this.LibroAsociadoSemilleroInv = new HashSet<LibroAsociadoSemilleroInv>();
            this.ProyectoAsociadoSemilleroInv = new HashSet<ProyectoAsociadoSemilleroInv>();
            this.ReconociemientoAsociadoSemilleroInv = new HashSet<ReconociemientoAsociadoSemilleroInv>();
        }
    
        public decimal Id { get; set; }
        public string Nombre { get; set; }
        public decimal Coordinador { get; set; }
        public string ObjetivoGeneral { get; set; }
        public string ObjetivosEspecificos { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public decimal LineaInvestigacion { get; set; }
        public string Enlace { get; set; }
        public System.DateTime FechaUpdate { get; set; }
        public Nullable<decimal> Estado { get; set; }
        public string Tags { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActividadAsociadoSemilleroInv> ActividadAsociadoSemilleroInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticuloAsociadoSemilleroInv> ArticuloAsociadoSemilleroInv { get; set; }
        public virtual Estado Estado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoAsociadoSemilleroInv> EventoAsociadoSemilleroInv { get; set; }
        public virtual Integrante Integrante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegranteSemilleroInvestigacion> IntegranteSemilleroInvestigacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibroAsociadoSemilleroInv> LibroAsociadoSemilleroInv { get; set; }
        public virtual LineaInvestigacion LineaInvestigacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoAsociadoSemilleroInv> ProyectoAsociadoSemilleroInv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReconociemientoAsociadoSemilleroInv> ReconociemientoAsociadoSemilleroInv { get; set; }
    }
}
